INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'MEMBER_CREATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (2, 'MEMBER_READ');
INSERT INTO AUTHORITY(ID, NAME) VALUES (3, 'MEMBER_UPDATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (4, 'MEMBER_DELETE');